# Generated by Django 4.2.4 on 2023-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_options_company_company__name__idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Diagnosis registry name')),
                ('short_name', models.CharField(max_length=25, verbose_name='Diagnosis registry short name')),
                ('oncor_tag_rid', models.CharField(max_length=25, verbose_name='Oncor tag @rid')),
                ('medical_record_transcript_settings', models.JSONField(verbose_name='Settings of medical record transcript')),
            ],
            options={
                'verbose_name': 'Diagnosis registry',
                'verbose_name_plural': 'Diagnosis registers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('rid', models.CharField(primary_key=True, serialize=False, verbose_name='Patient rid')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddIndex(
            model_name='diagnosisregistry',
            index=models.Index(fields=['name'], name='dia_reg__name__idx'),
        ),
    ]
