# Generated by Django 4.2.4 on 2023-08-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diagnosisregistry_patient_delete_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisregistry',
            name='medical_record_transcript_settings',
            field=models.JSONField(blank=True, null=True, verbose_name='Settings of medical record transcript'),
        ),
        migrations.AlterField(
            model_name='diagnosisregistry',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnosis registry name'),
        ),
        migrations.AlterField(
            model_name='diagnosisregistry',
            name='oncor_tag_rid',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Oncor tag @rid'),
        ),
        migrations.AlterField(
            model_name='diagnosisregistry',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Diagnosis registry short name'),
        ),
    ]
