# Generated by Django 4.2.4 on 2023-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_diagnosisregistry_medical_record_transcript_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemdDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptn_id', models.CharField(db_index=True, max_length=16, verbose_name='Patient @rid')),
                ('ptn_code', models.CharField(max_length=16, null=True, verbose_name='Patient extra abbreviation')),
                ('ptn_tags', models.JSONField(null=True, verbose_name='Patient tags')),
                ('rc_id', models.DateTimeField(db_index=True, max_length=16, verbose_name='SEMD record @rid')),
                ('time_rc', models.DateTimeField(null=True, verbose_name='SEMD time')),
                ('document_type', models.CharField(max_length=8, null=True, verbose_name='SEMD type')),
                ('nsi_doc_type', models.CharField(max_length=8, null=True, verbose_name='SEMD nsi type')),
                ('profile', models.CharField(max_length=8, null=True, verbose_name='SEMD profile')),
                ('author_mo_oid', models.CharField(max_length=64, null=True, verbose_name='SEMD author MO OID')),
                ('author_snils', models.CharField(max_length=14, null=True, verbose_name='SEMD author SNILS')),
                ('author_post', models.CharField(max_length=64, null=True, verbose_name='SEMD author post OID')),
                ('internal_message_id', models.CharField(max_length=64, null=True, verbose_name='SEMD internal_message_id')),
                ('external_message_id', models.CharField(max_length=64, null=True, verbose_name='SEMD external_message_id')),
                ('diagnosis_mkb10', models.CharField(db_index=True, max_length=10, verbose_name='Diagnosis mkb10 code')),
                ('diagnosis_date', models.DateField(null=True, verbose_name='Diagnosis set date')),
                ('diagnosis_code1379', models.CharField(max_length=10, null=True, verbose_name='Diagnosis SEMD section')),
                ('diagnosis_code1076', models.CharField(max_length=10, null=True, verbose_name='Diagnosis accuracy type')),
                ('diagnosis_code1077', models.CharField(max_length=10, null=True, verbose_name='Diagnosis type')),
            ],
            options={
                'verbose_name': 'Patient-SEMD-diagnosis',
                'verbose_name_plural': 'Patient-SEMD-diagnosis cube',
                'ordering': ['id'],
            },
        ),
    ]
