# Generated by Django 4.2.4 on 2023-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_semddiagnosis_rc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semddiagnosis',
            name='rc_id',
            field=models.CharField(db_index=True, max_length=16, verbose_name='SEMD record @rid'),
        ),
    ]
