# Generated by Django 4.2.4 on 2023-09-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_semddiagnosis_ptn_mo_oid_semdservice_ptn_mo_oid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='semddiagnosis',
            index=models.Index(fields=['ptn_id', 'diagnosis_mkb10', 'time_rc'], name='api_semddiagnosis_ptn_dz_rcdat'),
        ),
    ]
