# Generated by Django 4.2.4 on 2023-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_semddiagnosis_api_semddiagnosis_ptn_dz_rcdat'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='semdservice',
            index=models.Index(fields=['ptn_id', 'service_code', 'time_rc'], name='api_semdservice_ptn_srv_rcdat'),
        ),
    ]
