# Generated by Django 4.2.4 on 2023-09-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_semdservice_api_semdservice_ptn_srv_rcdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosisMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptn_id', models.CharField(db_index=True, max_length=16, verbose_name='Patient @rid')),
                ('ptn_code', models.CharField(max_length=16, null=True, verbose_name='Patient extra abbreviation')),
                ('ptn_mo_oid', models.CharField(max_length=64, null=True, verbose_name='Patient MO OID')),
                ('ptn_tags', models.JSONField(null=True, verbose_name='Patient tags')),
                ('diagnosis_mkb10', models.CharField(db_index=True, max_length=10, verbose_name='Diagnosis mkb10 code')),
                ('diagnosis_date', models.DateField(null=True, verbose_name='Diagnosis set date')),
                ('diagnosis_milestones', models.JSONField(null=True, verbose_name='Diagnosis milestones')),
            ],
            options={
                'verbose_name': 'Patient-Diagnosis',
                'verbose_name_plural': 'Patient-Diagnosis cube',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['ptn_id', 'diagnosis_mkb10', 'diagnosis_date'], name='api_p_d_milestones_ptn_dz_dat')],
            },
        ),
    ]
