# Generated by Django 4.2.4 on 2023-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_patientdiagnosismilestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnosismilestones',
            name='diagnosis_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Diagnosis set date'),
        ),
    ]
