# Generated by Django 4.2.4 on 2023-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_patientdiagnosismilestones_diagnosis_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patientdiagnosismilestones',
            index=models.Index(fields=['ptn_id', 'diagnosis_date'], name='api_p_d_milestones_ptn_dat'),
        ),
    ]
