# Generated by Django 4.2.4 on 2023-11-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_patient_birthday_patient_code_patient_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptn_id', models.CharField(db_index=True, max_length=16, verbose_name='Patient @rid')),
                ('rc_id', models.CharField(db_index=True, max_length=16, verbose_name='Record @rid')),
                ('rc_type', models.CharField(db_index=True, max_length=32, verbose_name='Record type')),
                ('rc_time', models.DateTimeField(db_index=True, null=True, verbose_name='Record time')),
                ('rc_time_in', models.DateTimeField(null=True, verbose_name='Record time in')),
                ('rc_time_out', models.DateTimeField(null=True, verbose_name='Record time out')),
                ('rc_summary', models.JSONField(null=True, verbose_name='Record summary')),
            ],
            options={
                'verbose_name': 'Patient Cancer Register Record',
                'verbose_name_plural': 'Patient Cancer Register Records',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['ptn_id', 'rc_type', 'rc_time'], name='api_patientrecord_ptn_typ_tim'), models.Index(fields=['ptn_id', 'rc_time'], name='api_patientrecord_ptn_tim')],
            },
        ),
    ]
