# Generated by Django 4.2.4 on 2023-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_patientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_in_cancer_register',
            field=models.BooleanField(default=False, verbose_name='Patient is in Cancer register flag'),
            preserve_default=False,
        ),
    ]
