# Generated by Django 4.2.4 on 2023-11-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_patient_is_in_cancer_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptn_id', models.CharField(db_index=True, max_length=16, verbose_name='Patient @rid')),
                ('rc_id', models.CharField(db_index=True, max_length=16, verbose_name='Record @rid')),
                ('diagnosis_date', models.DateField(db_index=True, null=True, verbose_name='Diagnosis set date')),
                ('diagnosis_mkb10', models.CharField(db_index=True, max_length=10, verbose_name='Diagnosis mkb10 code')),
                ('primacy', models.CharField(max_length=64, null=True, verbose_name='Diagnosis primacy')),
                ('morph_class_disabled', models.CharField(max_length=64, null=True, verbose_name='Diagnosis morph_class_disabled')),
                ('morph_class_child_count', models.CharField(max_length=64, null=True, verbose_name='Diagnosis morph_class_child_count')),
                ('tumor_main', models.CharField(max_length=64, null=True, verbose_name='Diagnosis tumor_main')),
                ('tumor_side', models.CharField(max_length=64, null=True, verbose_name='Diagnosis tumor_side')),
                ('how_discover', models.CharField(max_length=64, null=True, verbose_name='Diagnosis how_discover')),
                ('method', models.CharField(max_length=64, null=True, verbose_name='Diagnosis method')),
                ('plural', models.CharField(max_length=64, null=True, verbose_name='Diagnosis plural')),
                ('res_autopsy', models.CharField(max_length=64, null=True, verbose_name='Diagnosis res_autopsy')),
                ('why_old', models.CharField(max_length=64, null=True, verbose_name='Diagnosis why_old')),
                ('loc_met', models.CharField(max_length=64, null=True, verbose_name='Diagnosis loc_met')),
                ('tnm_t', models.CharField(max_length=64, null=True, verbose_name='Diagnosis tnm_t')),
                ('tnm_n', models.CharField(max_length=64, null=True, verbose_name='Diagnosis tnm_n')),
                ('tnm_m', models.CharField(max_length=64, null=True, verbose_name='Diagnosis tnm_m')),
                ('tnm_g', models.CharField(max_length=64, null=True, verbose_name='Diagnosis tnm_g')),
                ('stage', models.CharField(max_length=64, null=True, verbose_name='Diagnosis stage')),
            ],
            options={
                'verbose_name': 'Patient Cancer Register diagnosis',
                'verbose_name_plural': 'Patient Cancer Register diagnoses',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['ptn_id', 'diagnosis_mkb10', 'diagnosis_date'], name='api_patientdiagnosis_ptn_dz_dt'), models.Index(fields=['ptn_id', 'diagnosis_date'], name='api_patientdiagnosis_ptn_dat')],
            },
        ),
    ]
