# Generated by Django 4.2.4 on 2023-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_patientdiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='status',
            field=models.CharField(max_length=64, null=True, verbose_name='Diagnosis status'),
        ),
    ]
