# Generated by Django 4.2.4 on 2023-12-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_patientsemd_semd_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsemd',
            name='ptn_code',
            field=models.CharField(default='', max_length=16, verbose_name='Patient code'),
            preserve_default=False,
        ),
    ]
