# Generated by Django 4.2.4 on 2023-12-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_patientsemd_ptn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsemd',
            name='content_error',
            field=models.CharField(db_index=True, default='', max_length=1024, verbose_name='Content error'),
            preserve_default=False,
        ),
    ]
