# Generated by Django 4.2.4 on 2023-12-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_patientsemd_content_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsemd',
            name='diagnosis_error',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Diagnosis error'),
        ),
    ]
