# Generated by Django 4.2.4 on 2023-12-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_patientsemd_diagnosis_error'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientSEMD',
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='morph_class_sname',
            field=models.CharField(max_length=64, null=True, verbose_name='Diagnosis morph_class_s_name'),
        ),
    ]
