# Generated by Django 4.2.4 on 2023-12-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_patientsemd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSEMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptn_id', models.CharField(db_index=True, max_length=16, verbose_name='Patient @rid')),
                ('ptn_code', models.CharField(max_length=16, verbose_name='Patient code')),
                ('rc_sms_id', models.CharField(max_length=16, verbose_name='SMS Record @rid')),
                ('rc_cda_id', models.CharField(max_length=16, verbose_name='CDA Record @rid')),
                ('is_external_semd', models.BooleanField(verbose_name='External SEMD flag')),
                ('is_external_semd_sendable', models.BooleanField(null=True, verbose_name='External SEMD flag')),
                ('send_task_step', models.CharField(max_length=64, null=True, verbose_name='Send task step')),
                ('send_task_status', models.CharField(max_length=64, null=True, verbose_name='Send task status')),
                ('sms_status', models.JSONField(null=True, verbose_name='SMS status')),
                ('cda_status', models.JSONField(null=True, verbose_name='CDA status')),
                ('rc_time', models.DateTimeField(db_index=True, verbose_name='SEMD time')),
                ('cda_local_date', models.DateField(db_index=True, verbose_name='SEMD date')),
                ('attachment', models.CharField(db_index=True, max_length=64, verbose_name='Attachment id')),
                ('profile', models.CharField(max_length=8, verbose_name='SEMD profile')),
                ('soap_doc_type', models.CharField(max_length=8, null=True, verbose_name='SEMD type')),
                ('author_mo_oid', models.CharField(max_length=64, null=True, verbose_name='Author MO oid')),
                ('author_mo_dpt_oid', models.CharField(max_length=64, null=True, verbose_name='Author MO department oid')),
                ('author_snils', models.CharField(max_length=14, null=True, verbose_name='Author SNILS')),
                ('author_post', models.CharField(max_length=8, null=True, verbose_name='Author post id')),
                ('diagnosis_mkb10', models.CharField(max_length=10, null=True, verbose_name='Diagnosis mkb10 code')),
                ('diagnosis_date', models.DateField(null=True, verbose_name='Diagnosis date')),
                ('diagnosis_code197', models.CharField(max_length=32, null=True, verbose_name='Diagnosis code197')),
                ('diagnosis_code1076', models.CharField(max_length=8, null=True, verbose_name='Diagnosis code1076')),
                ('diagnosis_code1077', models.CharField(max_length=8, null=True, verbose_name='Diagnosis code1077')),
                ('is_cancer_diagnosis', models.BooleanField(verbose_name='Cancer diagnosis flag')),
                ('is_precancer_diagnosis', models.BooleanField(verbose_name='Precancer diagnosis flag')),
                ('diagnoses', models.JSONField(null=True, verbose_name='SEMD diagnoses')),
                ('is_cancer_diagnoses', models.BooleanField(verbose_name='Cancer diagnoses flag')),
                ('is_precancer_diagnoses', models.BooleanField(verbose_name='Precancer diagnoses flag')),
                ('services', models.JSONField(null=True, verbose_name='SEMD services')),
                ('cda_time', models.DateTimeField(null=True, verbose_name='CDA time')),
                ('sms_type', models.CharField(max_length=32, null=True, verbose_name='SMS type')),
                ('is_in_cancer_register', models.BooleanField(verbose_name='Patient is in Cancer register flag')),
                ('has_cancer_diagnosis', models.BooleanField(verbose_name='Patient has cancer diagnosis flag')),
                ('has_precancer_diagnosis', models.BooleanField(verbose_name='Patient has precancer diagnosis flag')),
                ('rc_diagnosis_mkb10', models.CharField(max_length=10, null=True, verbose_name='Cancer Register diagnosis mkb10 code')),
                ('rc_diagnosis_date', models.DateField(null=True, verbose_name='Cancer Register diagnosis date')),
                ('semd_content', models.JSONField(null=True, verbose_name='SEMD content')),
                ('content_error', models.CharField(db_index=True, max_length=300, verbose_name='Content error')),
                ('diagnosis_error', models.CharField(db_index=True, max_length=150, verbose_name='Diagnosis error')),
            ],
            options={
                'verbose_name': 'Patient SEMD',
                'verbose_name_plural': 'Patient SEMDs',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['ptn_id', 'soap_doc_type', 'cda_local_date'], name='api_patientsemd_ptn_typ_dat'), models.Index(fields=['ptn_id', 'cda_local_date'], name='api_patientsemd_ptn_dat')],
            },
        ),
    ]
