# Generated by Django 4.2.4 on 2023-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_patientsemd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsemd',
            name='rc_cda_id',
            field=models.CharField(max_length=16, null=True, verbose_name='CDA Record @rid'),
        ),
        migrations.AlterField(
            model_name='patientsemd',
            name='rc_sms_id',
            field=models.CharField(max_length=16, null=True, verbose_name='SMS Record @rid'),
        ),
    ]
