# Generated by Django 4.2.4 on 2023-12-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_patientsemd_rc_cda_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsemd',
            name='attachment',
            field=models.CharField(max_length=64, null=True, verbose_name='Attachment id'),
        ),
    ]
